(ns app.core
  (:require [reagent.core :as r]
            [reagent.dom :as dom]
            [stylo.core :refer [c c?]]
            [reitit.frontend :as rf]
            [reitit.frontend.easy :as rfe]
            [reitit.coercion.spec :as rss]))

(def compiler
  (r/create-compiler {:function-components true}))

(defn p
  ([content]
   [:p {:class (c [:mt 1] :text-base :text-gray-500)}
    content])
  ([content & other-content]
   [:p {:class (c [:mt 1] :text-base :text-gray-500)}
    content other-content]))

(defn pre-bash [content] 
   [:div {:style {:background-color :black :width :min-content :border-radius "6px"}
              :class (c [:m 1])}
        [:pre {:class (c [:text :white])}
         content]])

(defn heading [content]
  [:h1 {:class (c [:m 1] :text-3xl :inline-block :extrabold [:text :gray-900] :tracking-tight)}
   content])

(defn a 
  ([link] 
   (a link link))
  ([link description]
    [:a {:href link
         :class (c [:text :blue-300] :underline)} description]))

(defn about []
  [:div {:class (c :w-full :flex)}
   [:div {:class (c [:w-min 0] :flex-auto [:px 4])}
    [:div {:class (c [:pb 10] :border-b [:border :gray-200] [:mb 10])} 
     [:p {:class (c [:m 1] :text-base :text-gray-500)}
   "StyloCSS library is based on macro, so we need some alchemy to make it work in ClojureScript environment.
    We assume that the result will worth the effort. It was inspired by Tailwind CSS. 
    It develops an idea of storing all css in one place without actually touching any .css file.
    Intall the Style library and keep your focus on styling, not typing. Let the macro do the rest of routine."]]]])

(defn installation []
  [:div
   (heading "Installation")
   (p  "Learn to set up shadow-cljs from the scratch in your project. ")
   (p "1. We create a shadowcljs template:")
   (pre-bash "lein new shadow-cljs shadow-example +reagent")
   (p "Don't forget to install all necessary js packages: ")
   (pre-bash "npm install")
   (p "Other available options of shadow-cljs are given here: ")
   (a "https://github.com/shadow-cljs/lein-template")
   (p "2. Add " [:pre "[stylo-css \"0.1.0 \"]"] " into dependencies.")
   (p " 3. Open up your shadow-cljs.edn configuration file and add")
   (pre-bash ":build-hooks [(stylo.shadow/reload {PATH-TO-CSS})]")
   (p "  into the :app configuration. {PATH-TO-CSS} - is a path where the css file will be generated.")
   (p "  Our configuration should look like this: ")
   (pre-bash "{... 
                    :builds
                      {:app 
                         {... 
                            :build-hooks [(stylo.shadow/reload \"public/out/stylo/css/stylo.css\")]}}}")

   (p  "4. Open public/index.html file, it is generated by shadow-cljs by default. We should add the new source of css into it. ")
   (p "Add the following into the <head> </head> section: ")
   (pre-bash " <link href= {PATH-TO-CSS} rel= \"stylesheet\">")
   (p "5. So, you it is time to use the library. 
           Comprehensive documetation may be read by the link:  ")
   (a "github.com/stylo-css/docs")
   (p "  The basic syntax is the following: ")

   (pre-bash "[:div {:class (c [:pt 8] :h-screen)}] ")
   (p "c - is our macro, it waits for classes alias as arguments ")
   (p ":h-screen [:pt 8] - class alias ")
   (p "when class needs some configuration - it is passed as a vector [:pt 8] - where :pt is class alias and 6 - it's value ")])


(defn home-page []
  [:div
   [:h2 "Welcome to frontend"]])

(defonce match (r/atom nil))

(defn current-page []
  [:div
   [:ul
    [:li [:a {:href (rfe/href ::frontpage)} "About"]]
    [:li [:a {:href (rfe/href ::about)} "Installation"]]]
   (when @match
     (let [view (:view (:data @match))]
       [view @match]))])

(def routes
  [["/"
    {:name ::frontpage
     :view about}]

   ["/about"
    {:name ::about
     :view installation}]])

(defn init! []
  (rfe/start!
   (rf/router routes {:data {:coercion rss/coercion}})
   (fn [m] (reset! match m))
    ;; set to false to enable HistoryAPI
   {:use-fragment true})
  (dom/render
   [current-page]
   (js/document.getElementById "app")
   compiler))

(init!)

