(ns components.default
  (:require [components.hiccup :refer [h1 h3
                                       p1 p3 a
                                       pre-bash code
                                       block]]
            [stylo.core :refer [c]]))

(defn about
  []

  (block

   (block
   (h1
    "Philosophy of library.")
    (p1
     "StyloCSS develops an idea of storing all css in one place without actually touching any .css file.")
    (p1 "It was inspired by Tailwind CSS. But we want to go far beyond.")
    (p1
     "Library develops an idea of storing all css in one place without actually touching any .css file.")
    (p1 "Install the Stylo library and keep your focus on styling, not typing. Let the macro do the rest of routine. ")
    (p1
     " P.S. library is based on macro, so we need some alchemy to make it work in ClojureScript environment, ")
    (p1 " but we prepared " (a "#installation" "installation") " guide"))

  (block
   (h1 "Version and compatibility. ")
      (p1 "Latest version is 0.1.0")
      (p1 "Tested with: ")
      (p1 "Clojure 1.10.0")
      (p1 "ClojureScript 10.10.866")
      (p1 "Status: usable alpha."))

  (block
    (h1 "Distribution and license: ")
    (p1 "Copyright © belongs to HealthSamurai and contributors.")
    (p1 "Distributed under the Eclipse Public License 2.0")
    (p1 "Logo is a property of HealthSamurai, but you can make a T-shirt with it free of charge."))))

(defn installation
  []
  (block
   (block
    (h1 "Installation")
    (p1 "Learn to set up shadow-cljs from the scratch in your project. "))
   (block
    (h3 "Installing using shadow-cljs and Leiningen")
    (p3 "At first we need to create a new shadow-cljs template.")
    (pre-bash "lein new shadow-cljs shadow-example +reagent")
    (p3 "Don't forget to install all necessary js packages: ")
    (pre-bash "npm install")
    (p3 "Other available options of shadow-cljs are given here: "
       (a "https://github.com/shadow-cljs/lein-template"))
    (p3 "Add  into " [:span {:class (c :font-bold)} "project.clj"] " dependencies: ")
    (code "[stylo-css \"0.1.0 \"]")
    (p3 "Open up your" [:span {:class (c :font-bold)} "shadow-cljs.edn"] "configuration file and add")
    (code "{ :build-hooks [(stylo.shadow/reload {PATH-TO-CSS})]}")
    (p3 "  into the :app configuration. {PATH-TO-CSS} - is a path where the css file will be generated.")
    (p3 " Our configuration should look like this: ")
    (code
     "{... \n :builds \n {:app \n \n {... \n \n :build-hooks [(stylo.shadow/reload \"public/out/stylo/css/stylo.css\")]}}}")
    (p3
     "Open public/index.html file, it is generated by shadow-cljs by default. We should add the new source of css into it. ")
    (p3 "Add the following into the <head> </head> section: ")
    (code " <link href= {PATH-TO-CSS} rel= \"stylesheet\">")
    (p3
     "So, you it is time to use the library.
           Comprehensive documetation may be read "  (a "/documentation" "here") ".")
    (p3 "  The basic syntax is the following: ")
    (code "[:div {:class (c [:pt 8] :h-screen)}] ")
    (p3 "c - is our macro, it waits for classes alias as arguments ")
    (p3 ":h-screen [:pt 8] - class alias ")
    (p3 "when class needs some configuration - it is passed as a vector
        [:pt 8] - where :pt is class alias and 6 - it's value "))
   (block
    (h3 "figwheel")
    (p3 "Documentation for figwheel is in progress."))))

(defn documentation
  []
  [:div
   (block
    (h1 "Documentation")
    (p1 "As being inspired by Tailwind CSS library - our documentation implements the same logic.")
    (p1 "Table of contents:")
    (p1 (a "/accessibility" "Accessibility."))
    (p1 "Background.")
    (p1 "Border.")
    (p1 "It must be links."))])
